### ISSUE TITLE
Thermostat > GetTemperatureReadingRequest - Version released Oct 16, 2025 of node-red-alexa-home-skill

### ISSUE THREAD

**Issue by dinogregorich** [hardillb/node-red-alexa-home-skill-web#198]
RE: Potential Issue - Thermostat > GetTemperatureReadingRequest
dinogregorich@gmail.com

Currently, all my switch devices are working correctly through Alexa.

The thermostats/temperature sensors is not receiving any requests when triggered through Alexa. I’ve already cleaned up and re-discovered all devices, Alexa successfully finds every one, but the Node-RED logs show no incoming requests for the thermostats, while switch requests do appear and function normally.

**Comment by hardillb** [comment]
Thanks, I will look at the weekend when I have some time

**Comment by hardillb** [comment]
Thermostat update deployed, please test

**Comment by hardillb** [comment]
Setting targets should work now, CUSTOM modes are no longer supported, just HEAT, COOL and AUTO

CUSTOM will get converted to AUTO

**Comment by C2Leu** [comment]
Tried the step to reproduce again and still get the same outcome

**Comment by GetUpdate** [comment]
Super Duper, it is working again ! 
THX GetUpdate

**Comment by GetUpdate** [comment]
Pitty it stoped again. 
Flow is not started at all (no output on debug node).
Thus Alexa respond: "xxx untersützt das nicht"   ->~ "xxx doesn't support this"
Als discover devices does not help.
Kind Regards GetUpdate
